script:
- export
- ls -al auto
- bash auto/magic.sh
env:
  secure: iHFnuYaSBZxiVPoOyjdrOHF/iPK9sggIGsNkr4RXYGDLDzC9F7s6rw9FnBFKqQcbzUGZIGiOTlzBEepLf9nEZpI4rU+Hy9KpO42Wdt9sGsAe6HW/ST0yzpd7BOJnUiV3PDizmVF9yH+QSBu0U43zJWs7bNjgAqzoouskahI6xRzDRt2Mg59B3htGkDJuGMjAlUdlojaLyGXnBz3QFirk3kP9TuCETX/e1CzZffFtkuvN3/LutQ1UmPwY9G/rCqtezsfkv5omnpG0zMnONJqQypfKfUkmUhHHCx/YmO0vLoJBjRK5yhOvEm9b5ptJeoNKRlrGc6EOfuAGPE8Vyzps8wVaNOk08AhuR7AvK1VaYdaYVkboCxlWzvNkleFwhY7ctwxTHpCWHPovgrlV6eKaIOtiWczyFXsEPuy7UJI29NsA1JeVZ2K86mi7WSUxhffpHrB/CuNGolO3VycAT4Mg1TdQbaKDpt2F830rO5U76YFwa0T7FdCRsYfl0GI10bvFYi078ElTGqSKLYCDlspLVEQRH2hMb2dNqbEh96/WFlkWbR4Q7jtv7eHR1pamfrbsRcpuEwn7JCVUc+NCkaEMSR4Lhah/pOpW2Xwv0oh5s6LGF37LxdHxLl/0M5Aa3LTKjL1sLVH7f/2vlokIvnzmzT699ObfginZzKLDdhCjh4U=
